# Generated by Django 5.2.7 on 2026-01-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='commande',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payment',
            field=models.CharField(choices=[('LIVRAISON', 'Paiement à la livraison'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money'), ('WAVE', 'Wave')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
