# Generated by Django 5.2.7 on 2025-10-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_alter_product_quantity_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
