# Generated by Django 5.2.7 on 2026-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_commande_options_commande_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
