# Generated by Django 5.2.7 on 2025-12-19 12:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_homepage_about_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
