# Generated by Django 5.2.7 on 2025-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_homepage_about_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='footer_bouton_message',
            field=models.CharField(default='Contactez-nous', max_length=255),
        ),
    ]
