# Generated by Django 5.2.7 on 2025-12-19 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_homepage_footer_bouton_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_message',
            field=ckeditor.fields.RichTextField(default='Bienvenue sur notre site'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_message',
            field=ckeditor.fields.RichTextField(default='Contactez-nous'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_bouton_message',
            field=models.CharField(default='En savoir plus', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_message',
            field=ckeditor.fields.RichTextField(default='© 2025 – Tous droits réservés'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='welcome_message',
            field=ckeditor.fields.RichTextField(default='Bienvenue sur notre site'),
        ),
    ]
