# Generated by Django 5.2.7 on 2026-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_homepage_about_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_link', models.URLField(blank=True)),
            ],
        ),
    ]
