# Generated by Django 5.2.7 on 2026-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_homeslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='action_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
